// Generated by CoffeeScript 1.8.0
var Gallery, currentTile;

currentTile = null;

Gallery = {
  galleryTemplate: compileHandlebarsTemplate('gallery-item-template'),
  loadMoreUrl: null,
  setLoadMoreUrl: function(url) {
    return Gallery.loadMoreUrl = url;
  },
  showGalleryModal: function(tile) {
    var context, modalTemplate;
    modalTemplate = compileHandlebarsTemplate('gallery-modal-template');
    context = {};
    context['notificationId'] = $(tile).data('id');
    context['originalUrl'] = $(tile).data('url');
    context['imageUrl'] = $(tile).data('image-url');
    context['videoUrl'] = $(tile).data('video-url');
    context['thumbnailUrl'] = $(tile).data('thumbnail-url');
    context['authorName'] = $(tile).data('author-name');
    context['avatarUrl'] = $(tile).data('author-avatar');
    context['text'] = $(tile).data('text');
    $('#galleryPopupContent').html(modalTemplate(context));
    return currentTile = tile;
  },
  previousTile: function() {
    var $currentTile, previousTile;
    if (currentTile !== null) {
      $currentTile = $(currentTile);
      previousTile = $currentTile.prev('a.gallery-thumbnail');
      if (previousTile.length) {
        Gallery.showGalleryModal(previousTile);
        return currentTile = previousTile;
      } else {
        return $('#galleryPopup').modal('hide');
      }
    }
  },
  nextTile: function() {
    var nextTile;
    if (currentTile !== null) {
      nextTile = $(currentTile).next('a.gallery-thumbnail');
      if (nextTile.length) {
        Gallery.showGalleryModal(nextTile);
        currentTile = nextTile;
      } else {
        Gallery.loadMore(Gallery.loadMoreUrl, function() {
          nextTile = $(currentTile).next('a.gallery-thumbnail');
          if (nextTile.length) {
            Gallery.showGalleryModal(nextTile);
            return currentTile = nextTile;
          }
        }, function() {
          return $('#galleryPopup').modal('hide');
        });
      }
    }
    return $('#gallery-content').empty();
  },
  loadingTile: function() {
    return $('#gallery-submenu').empty();
  },
  loadMore: function(url, onSuccess, onEmpty) {
    if (onSuccess == null) {
      onSuccess = null;
    }
    if (onEmpty == null) {
      onEmpty = null;
    }
    return $.get(url, {
      'since-notification-id': lastNotificationId,
      'media': currentMedia
    }, function(data) {
      if (data.trim() === '') {
        $('.load-more-btn').addClass('hidden');
        if (onEmpty != null) {
          onEmpty();
        }
        return false;
      }
      $('#galleryTiles').append(data);
      if (onSuccess != null) {
        onSuccess();
      }
      return true;
    });
  },
  acceptGalleryPost: function(notification) {
    return true;
  },
  updateGallery: function(data, ngController) {
    var elem;
    if (Gallery.acceptGalleryPost(data)) {
      data.isVideo = data.videoUrl !== null;
      elem = Gallery.galleryTemplate(data);
      return $('#galleryTiles').prepend(elem);
    }
  }
};
