// Generated by CoffeeScript 1.8.0
$(function() {
  var $fixedRows, $leaderboard, $nonFixedColumns, $scrollTable, bottom, header, scrollbarWidth, tableHeight, top;
  $leaderboard = $("#mainLeaderboard");
  $scrollTable = $leaderboard.find(".scroller");
  $fixedRows = $leaderboard.find(".fixed-rows table");
  $nonFixedColumns = $leaderboard.find(".non-fixed-header table");
  scrollbarWidth = 15;
  top = $leaderboard.offset().top;
  bottom = $("#footer").offset().top;
  header = $(".non-fixed-header").outerHeight(true);
  tableHeight = bottom - top - scrollbarWidth;
  if (tableHeight < 350) {
    tableHeight = 350;
  }
  $leaderboard.height(tableHeight);
  $nonFixedColumns.parent().width($leaderboard.width() - scrollbarWidth);
  $fixedRows.parent().height($leaderboard.height() - scrollbarWidth);
  return $scrollTable.scroll(function() {
    $fixedRows.css('top', $scrollTable.scrollTop() * -1);
    return $nonFixedColumns.css('left', $scrollTable.scrollLeft() * -1);
  });
});
