// Generated by CoffeeScript 1.8.0
var insightApp;

insightApp = angular.module('insight', ['ngRoute', 'nvd3ChartDirectives']);

insightApp.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/problems', {
      templateUrl: 'insight/template/all-problems',
      controller: 'allProblemsCtrl'
    }).when('/team-problems', {
      templateUrl: 'insight/template/team-problems',
      controller: 'allProblemsCtrl'
    }).when('/problem/:problemCode', {
      templateUrl: 'insight/template/problem-detail',
      controller: 'problemDetailCtrl'
    }).when('/languages', {
      templateUrl: 'insight/template/all-languages',
      controller: 'allLanguagesCtrl'
    }).when('/language/:languageName', {
      templateUrl: 'insight/template/language-detail',
      controller: 'languageDetailCtrl'
    }).when('/code', {
      templateUrl: 'insight/template/code-insight',
      controller: 'codeInsightCtrl'
    }).otherwise({
      redirectTo: '/problems'
    });
  }
]);

insightApp.factory('insightService', function($http, $interval) {
  var insightService, promise;
  insightService = {};
  promise = null;

  /*
    refresh rate for polling new insight data
   */
  insightService.refreshRate = 15000;

  /*
    loads data at the beginning and initiate insight data polling
    @param url server resource URL
    @param title temporary title before the title is loaded
    @param successFn initial success load function
    @param pollingFn function, which process periodically polled data
   */
  insightService.init = function(url, title, successFn, pollingFn) {
    if (promise != null) {
      $interval.cancel(promise);
    }
    console.log(promise);
    $("#insightHeadline").html("" + title);
    $http.get(url).success(successFn).error(function() {});
    return promise = $interval(function() {
      return $http.get(url).success(pollingFn);
    }, insightService.refreshRate);
  };

  /*
      get x value for pie chart
   */
  insightService.xFunction = function() {
    return function(d) {
      return d.key;
    };
  };

  /*
    get y value for pie chart
   */
  insightService.yFunction = function() {
    return function(d) {
      return d.value;
    };
  };

  /*
    get area color for pie chart
   */
  insightService.areaColor = function() {
    return function(d, i) {
      return d.data.color;
    };
  };

  /*
    construct a label for a pie chart
   */
  insightService.toolTipContentFunction = function() {
    return function(key, x, y, e, graph) {
      return '<p><strong>' + key + '</strong>' + ' - ' + Math.round(x) + ' submissions</p>';
    };
  };
  return insightService;
});


/*
  controller for view with all problems
 */

insightApp.controller('allProblemsCtrl', function($scope, $http, $interval, insightService) {
  $scope.data = {};
  $scope.problems = null;

  /*
    loads data at the beginning and initiate insight data polling
    @param contextPath app context path
    @param contestCode contest code
    @param title temporary title before the title is loaded
    @see insightService#init
   */
  $scope.init = function(contextPath, contestCode, title) {
    var url;
    url = "" + contextPath + "/" + contestCode + "/insight/ajax/all-problems";
    return $scope._init(url, contextPath, contestCode, title);
  };
  $scope.initForTeam = function(teamId, contextPath, contestCode, title) {
    var url;
    url = "" + contextPath + "/" + contestCode + "/insight/ajax/team-problems/" + teamId;
    console.log(url);
    return $scope._init(url, contextPath, contestCode, title);
  };
  $scope._init = function(url, contextPath, contestCode, title) {
    var pollingFn, successFn;
    successFn = function(data) {
      var element, _i, _len, _ref;
      _ref = data.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        $scope.data[element.code] = element.data;
      }
      return $scope.problems = data.problems;
    };
    pollingFn = function(data) {
      var element, _i, _len, _ref, _results;
      _ref = data.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        _results.push($scope.data[element.code] = element.data);
      }
      return _results;
    };
    return insightService.init(url, title, successFn, pollingFn);
  };

  /*
    get insight data for a given problem
    @param problemCode code of the problem
    @return problem insight data if exists
   */
  $scope.getChartData = function(problemCode) {
    if (($scope.data[problemCode] != null)) {
      return $scope.data[problemCode];
    }
  };

  /*
    count the total number of submissions per problem
    @param code of the problem
    @return total number of submissions
   */
  $scope.submissionsPerProblem = function(problemCode) {
    var elem, total, _i, _len, _ref;
    total = 0;
    if (($scope.data[problemCode] != null)) {
      _ref = $scope.data[problemCode];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elem = _ref[_i];
        total += elem.value;
      }
    }
    return total;
  };

  /*
    @see insightService#xFunction
   */
  $scope.xFunction = insightService.xFunction;

  /*
    @see insightService#yFunction
   */
  $scope.yFunction = insightService.yFunction;

  /*
    @see insightService#areaColor
   */
  $scope.areaColor = insightService.areaColor;

  /*
    @see insightService#toolTipContentFunction
   */
  return $scope.toolTipContentFunction = insightService.toolTipContentFunction;
});


/*
  controller for a detailed view of a single problem
 */

insightApp.controller('problemDetailCtrl', function($scope, $http, $interval, $routeParams, insightService) {
  $scope.data = null;

  /*
    loads data at the beginning and initiate insight data polling
    @param contextPath app context path
    @param contestCode contest code
    @param title temporary title before the title is loaded
    @see insightService#init
   */
  $scope.init = function(contextPath, contestCode, title) {
    var pollingFn, successFn, url;
    $("#insightHeadline").html("" + title + " " + $routeParams.problemCode);
    title = "" + title + " " + $routeParams.problemCode;
    url = "" + contextPath + "/" + contestCode + "/insight/ajax/problem/" + $routeParams.problemCode;
    successFn = function(data) {
      $scope.data = data.data;
      return $("#insightHeadline").html(data.title);
    };
    pollingFn = function(data) {
      return $scope.data = data.data;
    };
    return insightService.init(url, title, successFn, pollingFn);
  };

  /*
    @see insightService#xFunction
   */
  $scope.xFunction = insightService.xFunction;

  /*
    @see insightService#yFunction
   */
  $scope.yFunction = insightService.yFunction;

  /*
    @see insightService#areaColor
   */
  $scope.areaColor = insightService.areaColor;

  /*
    @see insightService#toolTipContentFunction
   */
  return $scope.toolTipContentFunction = insightService.toolTipContentFunction;
});


/*
  controller for view with all languages
 */

insightApp.controller('allLanguagesCtrl', function($scope, $http, $interval, insightService) {
  $scope.data = null;

  /*
    loads data at the beginning and initiate insight data polling
    @param contextPath app context path
    @param contestCode contest code
    @param title temporary title before the title is loaded
    @see insightService#init
   */
  return $scope.init = function(contextPath, contestCode, title) {
    var pollingFn, successFn, url;
    url = "" + contextPath + "/" + contestCode + "/insight/ajax/all-languages";
    successFn = function(data) {
      $scope.data = data.data;
      return $("#insightHeadline").html(data.title);
    };
    pollingFn = function(data) {
      return $scope.data = data.data;
    };
    return insightService.init(url, title, successFn, pollingFn);
  };
});


/*
  controller for a detailed view of a single language
 */

insightApp.controller('languageDetailCtrl', function($scope, $http, $interval, $routeParams, insightService) {
  $scope.data = null;
  $scope.languageName = $routeParams.languageName;

  /*
    loads data at the beginning and initiate insight data polling
    @param contextPath app context path
    @param contestCode contest code
    @param title temporary title before the title is loaded
    @see insightService#init
   */
  $scope.init = function(contextPath, contestCode, title) {
    var pollingFn, successFn, url;
    title = "" + title + " " + $routeParams.languageName;
    url = "" + contextPath + "/" + contestCode + "/insight/ajax/language/" + $routeParams.languageName;
    successFn = function(data) {
      $scope.data = data.data;
      return $("#insightHeadline").html(data.title);
    };
    pollingFn = function(data) {
      return $scope.data = data.data;
    };
    return insightService.init(url, title, successFn, pollingFn);
  };

  /*
    @see insightService#xFunction
   */
  $scope.xFunction = insightService.xFunction;

  /*
    @see insightService#yFunction
   */
  $scope.yFunction = insightService.yFunction;

  /*
    @see insightService#areaColor
   */
  $scope.areaColor = insightService.areaColor;

  /*
    @see insightService#toolTipContentFunction
   */
  return $scope.toolTipContentFunction = insightService.toolTipContentFunction;
});


/*
  controller for a vie with code insight
 */

insightApp.controller('codeInsightCtrl', function($scope, $http, $interval, insightService) {
  $scope.data = {};
  $scope.problems = null;
  $scope.mode = 'DIFF';

  /*
    loads data at the beginning and initiate insight data polling
    @param contextPath app context path
    @param contestCode contest code
    @param title temporary title before the title is loaded
    @see insightService#init
   */
  $scope.init = function(contextPath, contestCode, title) {
    var url;
    url = "" + contextPath + "/" + contestCode + "/insight/ajax/codeInsight";
    return $scope._init(url, contextPath, contestCode, title);
  };
  $scope._init = function(url, contextPath, contestCode, title) {
    var pollingFn, successFn;
    successFn = function(data) {
      $scope.data = data.data;
      return $scope.problems = data.problems;
    };
    pollingFn = function(data) {
      return $scope.data = data.data;
    };
    return insightService.init(url, title, successFn, pollingFn);
  };

  /*
    get insight data for a given problem
    @param problemCode code of the problem
    @return problem insight data if exists
   */
  $scope.getChartData = function(problemCode) {
    if (($scope.data[problemCode] != null)) {
      return $scope.data[problemCode];
    }
  };
  return $scope.toolTipContentFunction = function() {
    return function(key, x, y, e, graph) {
      var text;
      text = $scope.mode === 'DIFF' ? 'Has changed ' : 'Has total ';
      return '<p><strong>' + x + '</strong></p>' + "<p>" + text + Math.round(y) + ' lines in ' + key + ' min</p>';
    };
  };
});
