// Generated by CoffeeScript 1.8.0
var insightApp;

insightApp = angular.module('insight', ['ngRoute', 'nvd3ChartDirectives']);

insightApp.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/problems', {
      templateUrl: 'insight/template/all-problems',
      controller: 'allProblemsCtrl'
    }).when('/problem/:problemCode', {
      templateUrl: 'insight/template/problem-detail',
      controller: 'problemDetailCtrl'
    }).when('/languages', {
      templateUrl: 'insight/template/all-languages',
      controller: 'allLanguagesCtrl'
    }).when('/language/:languageName', {
      templateUrl: 'insight/template/language-detail',
      controller: 'languageDetailCtrl'
    }).when('/code', {
      templateUrl: 'insight/template/code-insight',
      controller: 'codeInsightCtrl'
    }).otherwise({
      redirectTo: '/problems'
    });
  }
]);

insightApp.factory('insightService', function() {
  var insightService;
  insightService = {};
  insightService.refreshRate = 5000;
  insightService.xFunction = function() {
    return function(d) {
      return d.key;
    };
  };
  insightService.yFunction = function() {
    return function(d) {
      return d.value;
    };
  };
  insightService.areaColor = function() {
    return function(d, i) {
      return d.data.color;
    };
  };
  insightService.toolTipContentFunction = function() {
    return function(key, x, y, e, graph) {
      return '<p><strong>' + key + '</strong>' + ' - ' + Math.round(x) + ' submissions</p>';
    };
  };
  return insightService;
});

insightApp.controller('allProblemsCtrl', function($scope, $http, $interval, insightService) {
  $scope.data = {};
  $scope.problems = null;
  $scope.init = function(contextPath, contestCode, title) {
    var completed;
    $("#insightHeadline").html("" + title);
    $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/all-problems").success(function(data) {
      var element, _i, _len, _ref;
      _ref = data.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        $scope.data[element.code] = element.data;
      }
      $scope.problems = data.problems;
      return $("#insightHeadline").html(data.title);
    }).error(function() {});
    return completed = $interval(function() {
      return $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/all-problems").success(function(data) {
        var element, _i, _len, _ref, _results;
        _ref = data.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          element = _ref[_i];
          _results.push($scope.data[element.code] = element.data);
        }
        return _results;
      });
    }, insightService.refreshRate);
  };
  $scope.getChartData = function(problemCode) {
    if (($scope.data[problemCode] != null)) {
      return $scope.data[problemCode];
    }
  };
  $scope.submissionsPerProblem = function(problemCode) {
    var elem, total, _i, _len, _ref;
    total = 0;
    if (($scope.data[problemCode] != null)) {
      _ref = $scope.data[problemCode];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elem = _ref[_i];
        total += elem.value;
      }
    }
    return total;
  };
  $scope.xFunction = insightService.xFunction;
  $scope.yFunction = insightService.yFunction;
  $scope.areaColor = insightService.areaColor;
  return $scope.toolTipContentFunction = insightService.toolTipContentFunction;
});

insightApp.controller('problemDetailCtrl', function($scope, $http, $interval, $routeParams, insightService) {
  $scope.data = null;
  $scope.init = function(contextPath, contestCode, title) {
    var completed;
    $("#insightHeadline").html("" + title + " " + $routeParams.problemCode);
    $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/problem/" + $routeParams.problemCode).success(function(data) {
      $scope.data = data.data;
      return $("#insightHeadline").html(data.title);
    }).error(function() {});
    return completed = $interval(function() {
      return $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/problem/" + $routeParams.problemCode).success(function(data) {
        return $scope.data = data.data;
      });
    }, insightService.refreshRate);
  };
  $scope.xFunction = insightService.xFunction;
  $scope.yFunction = insightService.yFunction;
  $scope.areaColor = insightService.areaColor;
  return $scope.toolTipContentFunction = insightService.toolTipContentFunction;
});

insightApp.controller('allLanguagesCtrl', function($scope, $http, $interval, insightService) {
  $scope.data = null;
  return $scope.init = function(contextPath, contestCode, title) {
    var completed;
    $("#insightHeadline").html("" + title);
    $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/all-languages").success(function(data) {
      $scope.data = data.data;
      return $("#insightHeadline").html(data.title);
    }).error(function() {});
    return completed = $interval(function() {
      return $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/all-languages").success(function(data) {
        return $scope.data = data.data;
      });
    }, insightService.refreshRate);
  };
});

insightApp.controller('languageDetailCtrl', function($scope, $http, $interval, $routeParams, insightService) {
  $scope.data = null;
  $scope.languageName = $routeParams.languageName;
  $scope.init = function(contextPath, contestCode, title) {
    var completed;
    $("#insightHeadline").html("" + title + " " + $routeParams.languageName);
    $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/language/" + $routeParams.languageName).success(function(data) {
      $scope.data = data.data;
      return $("#insightHeadline").html(data.title);
    }).error(function() {});
    return completed = $interval(function() {
      return $http.get("" + contextPath + "/" + contestCode + "/insight/ajax/language/" + $routeParams.languageName).success(function(data) {
        return $scope.data = data.data;
      });
    }, insightService.refreshRate);
  };
  $scope.xFunction = insightService.xFunction;
  $scope.yFunction = insightService.yFunction;
  $scope.areaColor = insightService.areaColor;
  return $scope.toolTipContentFunction = insightService.toolTipContentFunction;
});

insightApp.controller('codeInsightCtrl', function($scope, $http) {
  $scope.data = null;
  return $scope.init = function(contextPath, contestCode, title) {
    return $("#insightHeadline").html("" + title);
  };
});
