// Generated by CoffeeScript 1.8.0
var kioskApp, scrollMeDown, scrollMeUp, updateKioskFeed;

kioskApp = angular.module('kiosk', ['wu.masonry']);

kioskApp.controller('kioskFeedCtrl', function($scope, $sce) {
  $scope.notifications = {};
  $scope.init = function(notifications) {
    return $scope.$apply(function() {
      var i, _i, _ref, _results;
      $scope.notifications = notifications;
      _results = [];
      for (i = _i = 0, _ref = $scope.notifications.length - 1; _i <= _ref; i = _i += 1) {
        if ($scope.notifications[i].type === 'eventOpen') {
          $scope.notifications[i].body = JSON.parse($scope.notifications[i].body);
        }
        _results.push(console.log($scope.notifications[i]));
      }
      return _results;
    });
  };
  $scope.addTile = function(data) {
    return $scope.notifications.push(data);
  };
  $scope.refresh = function() {
    return $scope.$apply();
  };
  $scope.trustedHTML = function(html) {
    return $sce.trustAsHtml(html);
  };
  $scope.trustedResource = function(url) {
    if (url === null) {
      return "";
    }
    return $sce.trustAsResourceUrl(url);
  };
  return $scope.trustedYoutubeResource = function(url) {
    url += "?autoplay=1&loop=1";
    return $sce.trustAsResourceUrl(url);
  };
});

kioskApp.controller('kioskCalendarCtrl', function($scope) {
  $scope.days = [];
  $scope.init = function(days) {
    return $scope.$apply(function() {
      return $scope.days = days;
    });
  };
  return $scope.refresh = function() {
    return $scope.$apply();
  };
});

updateKioskFeed = function(data, ngController) {
  if (ngController == null) {
    ngController = null;
  }
  return ngController.addTile(data);
};

scrollMeUp = function() {
  $("html, body").animate({
    scrollTop: 0
  }, {
    duration: 5000
  });
  return setTimeout(function() {
    return scrollMeDown();
  }, 5000);
};

scrollMeDown = function() {
  $("html, body").animate({
    scrollTop: $(document).height()
  }, {
    duration: 5000
  });
  return setTimeout(function() {
    return scrollMeUp();
  }, 60000);
};
