// Generated by CoffeeScript 1.8.0
var scoreboard;

scoreboard = angular.module('quest', []);

scoreboard.controller('leaderboardCtrl', function($scope) {
  $scope.participants = [];
  $scope.challenges = [];
  return $scope.init = function(challenges, participants) {
    return $scope.$apply(function() {
      $scope.challenges = challenges;
      return $scope.participants = participants;
    });
  };
});
