// Generated by CoffeeScript 1.8.0
var scorebar;

scorebar = angular.module('worldMap', []);

scorebar.controller('worldMapCtrl', function($scope) {
  $scope.teams = [];
  $scope.config = {
    centered: null,
    config: null,
    projection: null,
    feature: null,
    teamCoorData: null,
    teamsWithCoor: new Array(),
    circleData: new Array(),
    circleSize: 5,
    teamCount: 0,
    fullColor: 255,
    darkColor: 100,
    refreshAnimationLength: 750,
    legendWidth: 1000,
    legendYTextBottomCorner: 200,
    legendYSpaceTitleBars: 5,
    legendYSpaceBottomTicks: 15,
    legendXCorner: 10,
    legendBarHeight: 10,
    legendLabelFrequency: 10
  };
  return $scope.renderMap = function(appPath, config) {
    var currentScale, currentTranslate, path, svg;
    $scope.config = $.extend({
      width: 1000,
      ratio: 0.65,
      scale: 150,
      translate: [490, 380],
      circleSize: 6
    }, config);
    $scope.config.teamCount = $scope.teams.length;
    $scope.config.legendWidth = $scope.config.width - 20;
    $scope.config.height = Math.round($scope.config.width * $scope.config.ratio);
    $scope.config.legendYTextBottomCorner = $scope.config.height - 40;
    currentScale = $scope.config.scale;
    currentTranslate = $scope.config.translate;
    svg = d3.select("#mapContainer").append("svg:svg").attr("width", $scope.config.width).attr("height", $scope.config.height);
    $scope.config.projection = d3.geo.mercator().scale(currentScale).translate(currentTranslate);
    path = d3.geo.path().projection($scope.config.projection);
    return d3.json(appPath + "/maps/world-countries.json", function(collection) {
      $scope.config.feature = svg.selectAll("path").data(collection.features).enter().append("svg:path").attr("d", function(d) {
        return path(d);
      }).attr("id", function(d) {
        return d.id;
      }).on("click", onCountryClick);
      return $scope.config.feature.append("svg:title").text(function(d) {
        return d.properties.name;
      });
    });
  };
});
